name: CI/CD con Bun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        bun-version: [1.1.26]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Verify Bun installation
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Restart the service
        run: sudo systemctl restart famed.service
