name: famed-ci/cd
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        bun-version: [1.1.26]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
